use customer_behavior;
select * from customer
limit 5;

-- Q1What is total revenue generated by male vs female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spend more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with highest product ratings?

SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amounts between standard and express shipping?

SELECT shipping_type,ROUND(AVG(purchase_amount),2) as "Average purchase" FROM customer 
WHERE shipping_type IN ('Standard','Express')
group by shipping_type;

-- Q5.Do subscribed customers spend more? Compare average spend and total revenue between subcribers and non-subscribers.

SELECT subscription_status, COUNT(customer_id) AS "Total Customers", ROUND(AVG(purchase_amount),2) AS "Average spend", SUM(purchase_amount) AS "total revenue"
FROM customer
GROUP BY subscription_status;

-- Q6.Which 5 products have the highest percentage of purchases with discount applied?

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) AS Discount_Rate
FROM customer
GROUP BY item_purchased
ORDER BY Discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
-- Used CTE here

WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New' 
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
select customer_segment, COUNT(*) AS ' Number Of Customers '
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 purchased products within each category?
-- Used window function and CTE

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subsribe?

SELECT subscription_status, 
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution desc;
